### ISSUE TITLE
样式 bug 反馈

### ISSUE THREAD

**Issue by AngusFu** [hilongjw/zhihu-beautify#2]
如图所示。
## 消息面板弹出时

![image](https://cloud.githubusercontent.com/assets/8180186/18259838/01b21632-741b-11e6-9976-a707465eddbe.png)
## 提问 button active 状态

这个也不算 bug，但总觉得不协调，貌似这还是知乎本身的样式。

![image](https://cloud.githubusercontent.com/assets/8180186/18259879/6c0f837a-741b-11e6-8478-02f8af5f6796.png)

**Comment by hilongjw** [comment]
@AngusFu button active 状态是个问题。消息面板弹出 我这里倒是正常的，不过我还是用改写css来处理一下

**Comment by hilongjw** [comment]
@AngusFu 已修复，另外推荐给系统安装 汉仪旗黑 字体（商用字体我就不发了，网上能找到） 视觉体验会更好

**Comment by AngusFu** [comment]
棒棒哒~
